changelog:
  categories:
    # Disabled in favour of release-please deps commit type
    # - title: Dependencies
    #   labels:
    #     - dependencies
    - title: Pull Requests
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - 'autorelease: tagged'
