changelog:
  categories:
    - title: Dependencies
      labels:
        - dependencies
    - title: Pull Requests
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - 'autorelease: tagged'
