.nh
.TH "DIEGO" "1" "Jul 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego-set-scrape - Enable or disable the scrape flag by default


.SH SYNOPSIS
.PP
\fBdiego set scrape {true|false|1|0|enabled|disabled} [flags]\fP


.SH DESCRIPTION
.PP
Enable or disable the scrape flag by default.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for scrape


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH EXAMPLE
.EX
diego set scrape true
diego s scrape false
.EE


.SH SEE ALSO
.PP
\fBdiego-set(1)\fP
