.nh
.TH "DIEGO" "1" "Jun 2025" "diego manual" "User Commands"

.SH NAME
diego-completion-powershell - Generate the autocompletion script for powershell


.SH SYNOPSIS
\fBdiego completion powershell [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for powershell.

.PP
To load completions in your current shell session:

.EX
diego completion powershell | Out-String | Invoke-Expression
.EE

.PP
To load completions for every new session, add the output of the above command
to your powershell profile.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for powershell

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
\fBdiego-completion(1)\fP
