.nh
.TH "DIEGO" "1" "Mar 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego-set - Set a configuration option


.SH SYNOPSIS
.PP
\fBdiego set [flags]\fP


.SH DESCRIPTION
.PP
Set a configuration option.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
.PP
\fBdiego(1)\fP, \fBdiego-set-all(1)\fP, \fBdiego-set-defaults(1)\fP, \fBdiego-set-format(1)\fP, \fBdiego-set-hugodir(1)\fP, \fBdiego-set-overwrite(1)\fP, \fBdiego-set-scrape(1)\fP, \fBdiego-set-shortcode(1)\fP
