.nh
.TH "DIEGO" "1" "Apr 2025" "diego manual" "User Commands"

.SH NAME
diego-set-defaults - Restore Diego default settings


.SH SYNOPSIS
\fBdiego set defaults [flags]\fP


.SH DESCRIPTION
Restore Diego default settings.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for defaults


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH EXAMPLE
.EX
diego set defaults true
diego s defaults 1
.EE


.SH SEE ALSO
\fBdiego-set(1)\fP
