.nh
.TH "DIEGO" "1" "Feb 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego-settings - Show current settings


.SH SYNOPSIS
.PP
\fBdiego settings [flags]\fP


.SH DESCRIPTION
.PP
Show current settings.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for settings


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
.PP
\fBdiego(1)\fP
