.nh
.TH "DIEGO" "1" "Apr 2025" "diego manual" "User Commands"

.SH NAME
diego-settings - Show current settings


.SH SYNOPSIS
\fBdiego settings [flags]\fP


.SH DESCRIPTION
Show current settings.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for settings


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
\fBdiego(1)\fP
