.nh
.TH "DIEGO" "1" "Apr 2025" "diego manual" "User Commands"

.SH NAME
diego-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
\fBdiego completion fish [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the fish shell.

.PP
To load completions in your current shell session:

.EX
diego completion fish | source
.EE

.PP
To load completions for every new session, execute once:

.EX
diego completion fish > ~/.config/fish/completions/diego.fish
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
\fBdiego-completion(1)\fP
