.nh
.TH "DIEGO" "1" "May 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego-import-instapaper - Import data from Instapaper


.SH SYNOPSIS
.PP
\fBdiego import instapaper {list} -i file [flags]\fP


.SH DESCRIPTION
.PP
Import data from Instapaper.


.SH OPTIONS
.PP
\fB--all\fP[=false]
	import every available field from CSV file

.PP
\fB--format\fP="yaml"
	output format for the Hugo data file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for instapaper

.PP
\fB--hugodir\fP="."
	path to the Hugo directory

.PP
\fB-i\fP, \fB--input\fP=""
	path to the CSV file (required)

.PP
\fB--overwrite\fP[=false]
	overwrite existent output data file

.PP
\fB--shortcode\fP[=false]
	generate a shortcode template for Hugo


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH EXAMPLE
.EX
diego import instapaper list -i list.csv
diego i ip list -i list.csv --all --shortcode

.EE


.SH SEE ALSO
.PP
\fBdiego-import(1)\fP
