.nh
.TH "DIEGO" "1" "Jun 2025" "diego manual" "User Commands"

.SH NAME
diego-set-all - Enable or disable the all flag by default


.SH SYNOPSIS
\fBdiego set all {true|false|1|0|enabled|disabled} [flags]\fP


.SH DESCRIPTION
Enable or disable the all flag by default.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for all


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH EXAMPLE
.EX
diego set all true
diego s all false
.EE


.SH SEE ALSO
\fBdiego-set(1)\fP
