.nh
.TH "DIEGO" "1" "Apr 2025" "diego manual" "User Commands"

.SH NAME
diego-set - Set a configuration option


.SH SYNOPSIS
\fBdiego set [flags]\fP


.SH DESCRIPTION
Set a configuration option.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
\fBdiego(1)\fP, \fBdiego-set-all(1)\fP, \fBdiego-set-defaults(1)\fP, \fBdiego-set-format(1)\fP, \fBdiego-set-hugodir(1)\fP, \fBdiego-set-overwrite(1)\fP, \fBdiego-set-scrape(1)\fP, \fBdiego-set-shortcode(1)\fP
