.nh
.TH "DIEGO" "1" "Jun 2025" "diego manual" "User Commands"

.SH NAME
diego-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
\fBdiego completion [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for diego for the specified shell.
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
\fBdiego(1)\fP, \fBdiego-completion-bash(1)\fP, \fBdiego-completion-fish(1)\fP, \fBdiego-completion-powershell(1)\fP, \fBdiego-completion-zsh(1)\fP
