.nh
.TH "DIEGO" "1" "May 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego-set-hugodir - Set path to the Hugo directory (default ".")


.SH SYNOPSIS
.PP
\fBdiego set hugodir path [flags]\fP


.SH DESCRIPTION
.PP
Set path to the Hugo directory (default ".").


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for hugodir


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH EXAMPLE
.EX
diego set hugodir ~/Projects/HugoBlog 
diego s hugodir ../Projects/HugoSite

.EE


.SH SEE ALSO
.PP
\fBdiego-set(1)\fP
