.nh
.TH "DIEGO" "1" "Apr 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego-import - Import data from various services into Hugo


.SH SYNOPSIS
.PP
\fBdiego import [flags]\fP


.SH DESCRIPTION
.PP
Import data from various services into Hugo.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for import


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH SEE ALSO
.PP
\fBdiego(1)\fP, \fBdiego-import-goodreads(1)\fP, \fBdiego-import-imdb(1)\fP, \fBdiego-import-instapaper(1)\fP, \fBdiego-import-letterboxd(1)\fP, \fBdiego-import-spotify(1)\fP, \fBdiego-import-youtube(1)\fP
