.nh
.TH "DIEGO" "1" "Apr 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego - DIEGO - A data importer extension for Hugo


.SH SYNOPSIS
.PP
\fBdiego [flags]\fP


.SH DESCRIPTION
.PP
DIEGO - A data importer extension for Hugo

.PP
Diego integrates with Hugo as a CLI tool to assist in importing and utilizing
exported social media data from various services on Hugo websites.

.PP
Complete documentation is available at 
\[la]https://github.com/ttybitnik/diego\[ra]\&.


.SH OPTIONS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for diego

.PP
\fB-v\fP, \fB--version\fP[=false]
	version for diego


.SH SEE ALSO
.PP
\fBdiego-completion(1)\fP, \fBdiego-import(1)\fP, \fBdiego-set(1)\fP, \fBdiego-settings(1)\fP
