.nh
.TH "DIEGO" "1" "Jun 2025" "diego manual" "User Commands"

.SH NAME
diego-set-hugodir - Set path to the Hugo directory (default ".")


.SH SYNOPSIS
\fBdiego set hugodir path [flags]\fP


.SH DESCRIPTION
Set path to the Hugo directory (default ".").


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for hugodir


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH EXAMPLE
.EX
diego set hugodir ~/Projects/HugoBlog 
diego s hugodir ../Projects/HugoSite
.EE


.SH SEE ALSO
\fBdiego-set(1)\fP
