.nh
.TH "DIEGO" "1" "Apr 2024" "diego manual" "User Commands"

.SH NAME
.PP
diego-set-defaults - Restore Diego default settings


.SH SYNOPSIS
.PP
\fBdiego set defaults [flags]\fP


.SH DESCRIPTION
.PP
Restore Diego default settings.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for defaults


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $HOME/.config/diego/config.yaml)


.SH EXAMPLE
.EX
diego set defaults true
diego s defaults 1

.EE


.SH SEE ALSO
.PP
\fBdiego-set(1)\fP
